import {readFileSync} from "node:fs";
import {test,expect,request} from "@playwright/test";
import {twelveBinaryTemplate} from "../../app/lib/contest-schema-fixtures";
test('Contest Library creates/imports inactive and activates explicitly without losing old contest',async({page,context})=>{
 if(process.env.E2E_ALLOW_MUTATIONS!=='true') throw new Error('Disposable only.');
 const headers={Origin:process.env.E2E_BASE_URL||'http://localhost:3000'};
 await page.goto('/admin');await page.getByLabel('Admin secret').fill(readFileSync(process.env.ADMIN_SECRET_FILE!,'utf8').trim());await page.getByRole('button',{name:'Enter admin',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Contest Library',exact:true})).toBeVisible();
 const api=await request.newContext({baseURL:headers.Origin,extraHTTPHeaders:{...headers,Cookie:(await context.cookies()).map(c=>`${c.name}=${c.value}`).join('; ')}});
 const old=await (await api.get('/api/admin/contest-schema')).json();
 await page.getByText('Create empty inactive contest from this configuration',{exact:true}).click();
 await page.getByLabel('New contest title').fill('Browser inactive 100-report draft');
 await page.getByLabel('New contest budget').fill('5');
 await page.getByRole('button',{name:'Create inactive draft',exact:true}).click();
 await expect(page.getByLabel('Selected contest',{exact:true})).not.toHaveValue(old.contestId);
 const id=await page.getByLabel('Selected contest',{exact:true}).inputValue();
 expect((await (await api.get('/api/admin/contest-schema')).json()).contestId).toBe(old.contestId);
 let state=await (await api.get(`/api/admin/contest-schema?contestId=${id}`)).json();
 const schema={...twelveBinaryTemplate,fields:twelveBinaryTemplate.fields.map(f=>({...f,type:'multiclass',allowedValues:['not_mentioned','absent','present'],allowNull:false}))};
 expect((await api.post('/api/admin/contest-schema',{headers,data:{action:'schema',contestId:id,expectedVersion:state.schema.version,expectedRevision:state.revision,schema}})).ok()).toBe(true);
 state=await (await api.get(`/api/admin/contest-schema?contestId=${id}`)).json();
 const reports=Array.from({length:100},(_,i)=>({external_id:`B${i}`,filename:`B${i}.txt`,split:i<20?'public':'private',report_text:`Synthetic fixture ${i}. Knee structures described. No private patient text.`}));
 await page.getByLabel('Report import',{exact:true}).fill(JSON.stringify(reports));
 // Explicit refresh reconciles a schema changed in another organizer API client.
 await page.reload(); await page.getByLabel('Selected contest',{exact:true}).selectOption(id);
 await page.getByLabel('Report import',{exact:true}).fill(JSON.stringify(reports));
 await page.getByRole('button',{name:'Import reports into selected empty draft',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Saved');
 state=await (await api.get(`/api/admin/contest-schema?contestId=${id}`)).json();expect(state.reports).toHaveLength(100);
 const answers=state.reports.map((r:{id:string})=>({report_id_or_filename:r.id,answer_values:Object.fromEntries(state.schema.fields.map((f:{key:string})=>[f.key,'not_mentioned']))}));
 expect((await api.post('/api/admin/contest-schema',{headers,data:{action:'answers',contestId:id,expectedVersion:state.schema.version,expectedRevision:state.revision,answers}})).ok()).toBe(true);
 await page.reload();await page.getByLabel('Selected contest',{exact:true}).selectOption(id);
 await expect(page.getByRole('button',{name:'Activate selected contest (paused)',exact:true})).toBeEnabled();
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Activate selected contest (paused)',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Contest selected');
 expect((await (await api.get('/api/admin/contest-schema')).json()).contestId).toBe(id);
 const stale=await api.post('/api/admin/challenge-phase',{headers:{...headers,'X-Contest-Id':old.contestId,'X-Contest-Version':String(old.schema.version)},data:{phase:'practice_open'}});expect(stale.status()).toBe(409);
 const missing=await api.post('/api/admin/challenge-phase',{headers,data:{phase:'practice_open'}});expect(missing.status()).toBe(409);
 const current=await api.post('/api/admin/challenge-phase',{headers:{...headers,'X-Contest-Id':id,'X-Contest-Version':String(state.schema.version)},data:{phase:'practice_open'}});expect(current.ok()).toBe(true);
 const library=await (await api.get('/api/admin/contests')).json();expect(library.contests.filter((c:{is_active:boolean})=>c.is_active)).toHaveLength(1);
 expect(library.contests.find((c:{id:string})=>c.id===old.contestId)).toBeTruthy();
 await page.getByLabel('Selected contest',{exact:true}).selectOption(old.contestId);
 await expect(page.getByText('Selected contest fields and answer keys',{exact:true})).toBeVisible();
 expect((await (await api.get('/api/admin/contest-schema')).json()).contestId).toBe(id);
 const unauth=await context.browser()!.newContext();expect((await unauth.request.get(`${headers.Origin}/api/admin/contests`)).status()).toBe(401);await unauth.close();await api.dispose();
});
