import {readFileSync} from 'node:fs';
import {test,expect,request} from '@playwright/test';
test('Contest Library creates/imports inactive and activates explicitly without losing old contest',async({page,context})=>{
 if(process.env.E2E_ALLOW_MUTATIONS!=='true')throw new Error('Disposable only.');
 const headers={Origin:process.env.E2E_BASE_URL||'http://localhost:3000'};
 await page.goto('/admin');await page.getByLabel('Admin secret').fill(readFileSync(process.env.ADMIN_SECRET_FILE!,'utf8').trim());await page.getByRole('button',{name:'Enter admin',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Run contest',exact:true})).toBeVisible();
 await expect(page.getByText('Start from a template',{exact:true})).toHaveCount(0);
 const api=await request.newContext({baseURL:headers.Origin,extraHTTPHeaders:{...headers,Cookie:(await context.cookies()).map(c=>`${c.name}=${c.value}`).join('; ')}});const old=await(await api.get('/api/admin/contest-schema')).json();
 await page.goto('/admin/contests');await page.getByRole('button',{name:'Create new contest',exact:true}).click();
 await page.getByLabel('Contest title',{exact:true}).fill('Synthetic browser lifecycle fixture');
 await page.getByRole('button',{name:'Create inactive draft',exact:true}).click();
 await expect(page).toHaveURL(/\/admin\/contests\/[a-f0-9-]+$/);
 const id=page.url().split('/').pop()!;
 expect((await(await api.get('/api/admin/contest-schema')).json()).contestId).toBe(old.contestId);
 await expect(page.getByText('Start from a template',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'3. Dataset',exact:true}).click();
 const reports=Array.from({length:8},(_,i)=>({external_id:`fixture_${i}`,filename:`fixture_${i}.txt`,split:i<3?'public':'private',report_text:`Synthetic example ${i}. No clinical source data.`}));
 await page.getByLabel('Reports JSON',{exact:true}).fill(JSON.stringify(reports));
 const posted=page.waitForResponse(r=>r.url().endsWith('/api/admin/contest-schema')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Import reports',exact:true}).click();expect((await posted).ok()).toBe(true);
 await expect(page.getByRole('status').last()).toContainText('Saved');
 let s=await(await api.get(`/api/admin/contest-schema?contestId=${id}`)).json();
 await page.getByLabel('Select draft report').selectOption(s.reports[0].id);await expect(page.getByLabel('Report text',{exact:true})).toBeVisible({timeout:5000});await page.getByLabel('Report text',{exact:true}).fill('Edited synthetic fixture only.');
 await page.getByRole('button',{name:'Save draft report',exact:true}).click();await expect(page.getByLabel('Report text',{exact:true})).toHaveCount(0);
 s=await(await api.get(`/api/admin/contest-schema?contestId=${id}`)).json();
 const answers=s.reports.map((r:{id:string})=>({report_id_or_filename:r.id,answer_values:Object.fromEntries(s.schema.fields.map((f:{key:string;allowedValues:string[]})=>[f.key,f.allowedValues[0]]))}));
 await page.getByLabel('Reference answers JSON').fill(JSON.stringify(answers));
 await page.getByRole('button',{name:'Validate and import answers',exact:true}).click();
 await expect.poll(async()=> (await(await api.get(`/api/admin/contest-schema?contestId=${id}`)).json()).ready).toBe(true);
 await page.getByRole('button',{name:'5. Review & activate',exact:true}).click();
 await expect(page.getByRole('button',{name:'Activate contest (paused)',exact:true})).toBeDisabled();
 await page.getByLabel('I have reviewed the clinical references',{exact:false}).check();page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'Activate contest (paused)',exact:true}).click();
 await expect(page).toHaveURL(/\/admin$/);await expect(page.getByRole('heading',{name:'Run contest',exact:true})).toBeVisible();
 s=await(await api.get(`/api/admin/contest-schema?contestId=${id}`)).json();expect(s.frozen).toBe(true);expect(s.history).toHaveLength(0);
 expect((await api.post('/api/admin/contest-schema',{headers,data:{action:'schema',contestId:id,expectedVersion:s.schema.version,expectedRevision:s.revision,schema:s.schema}})).status()).toBe(400);
 const stale=await api.post('/api/admin/challenge-phase',{headers:{...headers,'X-Contest-Id':old.contestId,'X-Contest-Version':String(old.schema.version)},data:{phase:'practice_open'}});expect(stale.status()).toBe(409);
 await page.goto(`/admin/contests/${id}`);await expect(page.getByRole('heading',{name:'Inspect contest',exact:true})).toBeVisible();
 await expect(page.getByRole('region',{name:'Contest Builder',exact:true})).toHaveCount(0);
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Duplicate as new draft',exact:true}).click();
 await expect(page).not.toHaveURL(new RegExp(`${id}$`));
 await expect(page.getByRole('region',{name:'Contest Builder',exact:true})).toBeVisible();
 const draft=await(await api.get(`/api/admin/contest-schema?contestId=${page.url().split('/').pop()}`)).json();
 expect(draft.frozen).toBe(false);expect(draft.ready).toBe(true);expect(draft.reports).toHaveLength(8);expect(draft.history).toHaveLength(0);
 expect((await(await api.get('/api/admin/contest-schema')).json()).contestId).toBe(id);
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const library=await(await api.get('/api/admin/contests')).json();expect(library.contests.some((c:{id:string})=>c.id===old.contestId)).toBe(true);
 const unauth=await context.browser()!.newContext();expect((await unauth.request.get(`${headers.Origin}/api/admin/contests`)).status()).toBe(401);await unauth.close();
});
