import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { test, expect } from "@playwright/test";
import { twelveBinaryTemplate } from "../../app/lib/contest-schema-fixtures";

test("one-editor team rehearsal: baseline, shared practice, frozen final, reveal and debrief", async ({ page, context }) => {
  if (process.env.E2E_ALLOW_MUTATIONS !== "true") throw new Error("Disposable synthetic fixture only.");
  const origin = process.env.E2E_BASE_URL || "http://localhost:3000";
  const headers = { Origin: origin };
  const secretFile = process.env.ADMIN_SECRET_FILE, accessFile = process.env.E2E_ACCESS_CODE_FILE;
  if (!secretFile || !accessFile) throw new Error("Protected fixture credential paths required.");
  await page.goto("/admin");
  await page.getByLabel("Admin secret").fill(readFileSync(secretFile,"utf8").trim());
  await page.getByRole("button", {name:"Enter admin",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Contest fields and answer keys"})).toBeVisible();
  let state = await (await context.request.get("/api/admin/contest-schema")).json();
  const fork = await context.request.post("/api/admin/contest-schema",{headers,data:{action:"fork",contestId:state.contestId,expectedVersion:state.schema.version}});
  expect(fork.ok()).toBe(true);
  state = await (await context.request.get("/api/admin/contest-schema")).json();
  const baseline = "Use the organizer definitions and explicit report evidence; distinguish negation and uncertainty. Abstain when you cannot decide.";
  const schema = {...twelveBinaryTemplate,education:{version:1,pipeline:"structured-v1",baselineInstructions:baseline}};
  expect((await context.request.post("/api/admin/contest-schema",{headers,data:{action:"schema",contestId:state.contestId,expectedVersion:state.schema.version,schema}})).ok()).toBe(true);
  state = await (await context.request.get("/api/admin/contest-schema")).json();
  const answers=state.reports.map((r:{id:string})=>({report_id_or_filename:r.id,answer_values:Object.fromEntries(state.schema.fields.map((f:{key:string,allowedValues:string[]})=>[f.key,f.allowedValues[0]]))}));
  expect((await context.request.post("/api/admin/contest-schema",{headers,data:{action:"answers",contestId:state.contestId,expectedVersion:state.schema.version,answers}})).ok()).toBe(true);
  expect((await context.request.post("/api/admin/evaluation-model",{headers,data:{model:"qwen/qwen3.5-9b"}})).ok()).toBe(true);
  expect((await context.request.post("/api/admin/challenge-phase",{headers,data:{phase:"practice_open"}})).ok()).toBe(true);
  const accessCode = readFileSync(accessFile,"utf8").trim();
  const auth = await (await context.request.post("/api/participants/validate",{headers,data:{accessCode}})).json();
  expect(auth.valid).toBe(true);
  const participantCode=auth.participantCode, participantToken=auth.participantToken;
  expect(typeof participantToken).toBe("string");
  const authHeader={Authorization:`Bearer ${participantToken}`};
  const common = await (await context.request.get("/api/education-summary",{headers:authHeader})).json();
  expect(common.simulated).toBe(true); expect(common.baseline.accuracy).toBeGreaterThanOrEqual(0);expect(common.hiddenBaseline).toBe(null);
  const submit = (kind:string,prompt:string,key:string)=>context.request.post(`/api/submissions/${kind}`,{headers:{...headers,"Idempotency-Key":key},data:{participantCode,participantToken,prompt}});
  const practice=await submit("public",baseline,"edu-browser-practice");expect(practice.ok()).toBe(true);
  const score=await practice.json();expect(score.score).toBe(common.baseline.accuracy);expect(score.feedback.clinicalComparisons).toHaveLength(common.reportCount);
  const replay=await (await submit("public",baseline,"edu-browser-practice")).json();expect(replay.publicSubmissionsUsed).toBe(1);
  expect((await context.request.post("/api/admin/evaluation-model",{headers,data:{model:"google/gemini-2.5-flash"}})).ok()).toBe(false);
  await page.goto("/");await page.getByLabel("Participant access code",{exact:true}).fill(accessCode);await page.getByRole("button",{name:"Enter workspace",exact:true}).click();
  await expect(page.getByText("SIMULATION — workflow rehearsal only.",{exact:false})).toBeVisible();
  await expect(page.getByPlaceholder("Write your clinical extraction strategy here...")).toHaveValue(baseline);
  await expect(page.getByRole("heading",{name:"Clinical definitions and scoring"})).toBeVisible();
  expect((await context.request.post("/api/admin/challenge-phase",{headers,data:{phase:"final_open"}})).ok()).toBe(true);
  // A teammate/browser can recover final text even when evaluation failed before
  // any prompt_run was written. Setup touches only the guarded disposable fixture.
  execFileSync(process.execPath, ["--conditions=react-server", "--import", "tsx", "scripts/fixture-failed-final.ts"], { env: process.env, stdio: "pipe" });
  const lockedText = "Recover these exact final instructions.\nUse explicit evidence, including negation.";
  const recovered = await (await context.request.get("/api/team-history", { headers: authHeader })).json();
  expect(recovered.final.instructions).toBe(lockedText); expect(recovered.final.status).toBe("failed");
  expect(recovered.practice).toHaveLength(1); expect(recovered.practice[0].instructions).toBe(baseline);
  expect(recovered.practice[0].score).toBeCloseTo(score.score, 3); expect(recovered.final.score).toBeUndefined();
  // Fresh browser context emulates loss of all local drafts; token only belongs to this team.
  const second = await page.context().browser()!.newContext(); const teammate = await second.newPage();
  await teammate.goto(origin); await teammate.getByLabel("Participant access code", { exact: true }).fill(accessCode);
  await teammate.getByRole("button", { name: "Enter workspace", exact: true }).click();
  await expect(teammate.getByRole("heading", { name: "Saved team instructions and practice results" })).toBeVisible();
  const practiceVersion = teammate.getByText(/^Practice 1 —/); await expect(practiceVersion).toBeVisible(); await practiceVersion.click();
  await expect(teammate.getByRole("button", { name: "Copy practice 1 instructions to editor" })).toBeVisible();
  await teammate.getByPlaceholder("Write your clinical extraction strategy here...").fill("Lost/replaced draft");
  teammate.once("dialog", dialog => dialog.accept());
  await teammate.getByRole("button", { name: "Restore locked final instructions to editor" }).click();
  await expect(teammate.getByPlaceholder("Write your clinical extraction strategy here...")).toHaveValue(lockedText);
  await second.close();
  expect((await submit("final", "Lost/replaced draft", "bad-recovery")).ok()).toBe(false);
  const final=await submit("final",lockedText,"edu-browser-final");expect(final.ok()).toBe(true);
  const hidden=await final.json();expect(hidden.resultsHidden).toBe(true);expect(hidden.finalScore).toBe(null);expect(hidden.score).toBeUndefined();expect(hidden.feedback).toBeUndefined();
  const status=await (await context.request.get(`/api/submissions/status?participantCode=${participantCode}`,{headers:authHeader})).json();expect(status.finalScore).toBe(null);expect(status.finalSubmissionUsed).toBe(true);
  expect((await submit("final",baseline+" changed","edu-browser-final-new")).ok()).toBe(false);
  expect((await context.request.post("/api/admin/challenge-phase",{headers,data:{phase:"ended"}})).ok()).toBe(true);
  const revealed=await (await submit("final",lockedText,"edu-browser-final")).json();expect(typeof revealed.score).toBe("number");
  const summary=await (await context.request.get("/api/education-summary",{headers:authHeader})).json();expect(summary.revealed).toBe(true);expect(typeof summary.hiddenBaseline.accuracy).toBe("number");
  await page.reload();await expect(page.getByRole("heading",{name:"Clinical debrief",exact:true})).toBeVisible();
  expect((await context.request.post("/api/admin/challenge-phase",{headers,data:{phase:"practice_open"}})).ok()).toBe(false);
  expect((await context.request.post("/api/run-sample",{headers,data:{}})).status()).toBe(410);
});
