import {test,expect} from '@playwright/test';
test('three-report sandbox: editable drafts, streamed predictions, persisted cooldown and score isolation',async({page,context})=>{
 if(process.env.E2E_SANDBOX_FIXTURE!=='true')test.skip(true,'Requires the dedicated synthetic sandbox fixture.');
 const origin=process.env.E2E_BASE_URL||'http://localhost:3000';
 const auth=await (await context.request.post('/api/participants/validate',{headers:{Origin:origin},data:{accessCode:'GPO-TEST-0001'}})).json();
 expect(auth.valid).toBe(true);
 await page.addInitScript(({code,token})=>{localStorage.setItem('great-prompt-off-participant-id',code);sessionStorage.setItem('great-prompt-off-participant-session-token',token);},{code:auth.participantCode,token:auth.participantToken});
 const common=await (await context.request.get('/api/challenge-data')).json();const id=common.challenge.id;
 const headers={Authorization:`Bearer ${auth.participantToken}`,Origin:origin};
 const status=await (await context.request.get(`/api/sandbox?contestId=${id}`,{headers})).json();
 expect(status.reports).toHaveLength(3);expect(status.enabled).toBe(true);
 expect((await context.request.get(`/api/sandbox?contestId=${id}`)).status()).toBe(401);
 expect((await context.request.post('/api/sandbox',{headers:{Authorization:headers.Authorization,Origin:'https://other.invalid'},data:{}})).status()).toBe(403);
 await page.setViewportSize({width:1280,height:900});await page.goto('/challenge');
 const panel=page.getByRole('region',{name:'Prompt Sandbox'});
 await expect(panel.getByRole('button',{name:'Sample 3',exact:true})).toBeVisible();
 const editor=page.getByPlaceholder('Write your clinical extraction strategy here...');await editor.fill('Extract explicitly documented findings.');
 const text=panel.getByLabel('Editable sample 1');await text.fill('Edited synthetic test sample.');await page.reload();
 await expect(panel.getByLabel('Editable sample 1')).toHaveValue('Edited synthetic test sample.');
 await panel.getByRole('button',{name:'Run sandbox · 3 reports',exact:true}).click();
 await expect(panel.getByText('Simulation: synthetic “no decision” outputs; no model called.')).toBeVisible();
 await expect(panel.getByRole('button',{name:/Ready in \d+s/})).toBeDisabled();
 await expect(panel.getByText('No decision',{exact:true})).toHaveCount(12);
 await page.reload();await expect(panel.getByRole('button',{name:/Ready in \d+s/})).toBeDisabled();
 const completed=await (await context.request.get(`/api/sandbox?contestId=${id}`,{headers})).json();
 expect(completed.job.results).toHaveLength(3);expect(completed.job.status).toBe('completed');
 const blocked=await context.request.post('/api/sandbox',{headers,data:{contestId:id,schemaVersion:1,prompt:'Other tab',reports:completed.reports,idempotencyKey:'browser-second-tab'}});
 expect(blocked.status()).toBe(429);expect(Number(blocked.headers()['retry-after'])).toBeGreaterThan(0);
 await panel.getByRole('button',{name:'Reset this sample',exact:true}).click();
 await expect(panel.getByLabel('Editable sample 1')).not.toHaveValue('Edited synthetic test sample.');
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
