import assert from 'node:assert/strict';
import {createDatabase} from '../app/lib/db/database';
import {getPool} from '../app/lib/db/pool';
import {mutateContestLibrary} from '../app/lib/db/contest-library';
import {admitSandbox,finishSandbox,sandboxStatus,appendSandboxResult} from '../app/lib/db/sandbox';
import {contestSchemaState,saveContestSchema} from '../app/lib/db/contest-schema';
import {twelveBinaryTemplate} from '../app/lib/contest-schema-fixtures';
async function main(){
 if(process.env.PGDATABASE!=='gpo_sandbox_test'||process.env.USE_REAL_LLM==='true')throw new Error('Disposable synthetic database only.');
 const db=createDatabase();
 const scoredTables=['submissions','prompt_runs','attempt_reservations','participant_attempt_overrides'];
 const scoredBefore=await Promise.all(scoredTables.map(t=>db.sql(`SELECT * FROM ${t} ORDER BY 1`)));
 const schema={...twelveBinaryTemplate,education:{version:1,pipeline:'structured-v1',baselineInstructions:'Extract explicit findings.'}};
 const {contestId}=await mutateContestLibrary(db,{action:'create',title:'Synthetic sandbox test',schema,evaluationModel:'qwen/qwen3.5-9b',practiceBudget:5});
 const [p]=await db.sql<{id:string}>("INSERT INTO participants(participant_code,access_code) VALUES('SB01','GPO-TEST-0001') RETURNING id");
 const [p2]=await db.sql<{id:string}>("INSERT INTO participants(participant_code,access_code) VALUES('SB02','GPO-TEST-0002') RETURNING id");
 const reports=await db.sql<{id:string;split:string}>(`INSERT INTO reports(challenge_id,external_id,filename,split,report_text) SELECT $1,'S'||n,'synthetic-'||n,CASE WHEN n<=20 THEN 'public'::report_split ELSE 'private'::report_split END,'Synthetic fixture '||n FROM generate_series(1,100) n RETURNING id,split`,[contestId]);
 const selected=reports.filter(r=>r.split==='private').slice(0,3).map(r=>r.id);
 const initial=await contestSchemaState(db,contestId);
 await saveContestSchema(db,{action:'answers',contestId,expectedVersion:1,expectedRevision:initial.revision,answers:initial.reports.map(r=>({report_id_or_filename:r.id,answer_values:Object.fromEntries(initial.schema.fields.map(f=>[f.key,'0']))}))});
 const answersBefore=await db.sql('SELECT * FROM answer_keys ORDER BY id');
 await mutateContestLibrary(db,{action:'sandbox',contestId,expectedVersion:1,sandboxEnabled:true,sampleIds:selected});
 assert.equal((await contestSchemaState(db,contestId)).ready,true,'Repartitioning a ready contest must preserve validated readiness');
 assert.deepEqual(await db.sql('SELECT * FROM answer_keys ORDER BY id'),answersBefore,'Repartition must not rewrite accepted answers');
 const counts=await db.sql<{split:string;n:number}>("SELECT split,count(*)::int n FROM reports WHERE challenge_id=$1 GROUP BY split ORDER BY split",[contestId]);
 assert.deepEqual(Object.fromEntries(counts.map(r=>[r.split,r.n])),{sample:3,public:20,private:77});
 const cs=await contestSchemaState(db,contestId);
 await saveContestSchema(db,{action:'answers',contestId,expectedVersion:1,expectedRevision:cs.revision,answers:cs.reports.map(r=>({report_id_or_filename:r.id,answer_values:Object.fromEntries(cs.schema.fields.map(f=>[f.key,'0']))}))});
 await db.sql("UPDATE challenges SET is_active=false WHERE is_active");
 await db.sql("UPDATE challenges SET is_active=true,event_phase='practice_open' WHERE id=$1",[contestId]);
 const before=await db.sql('SELECT * FROM reports ORDER BY id');
 const input={contestId,schemaVersion:1,idempotencyKey:'synthetic-run-1',prompt:'Use explicit evidence',reports:selected.map((id,i)=>({id,text:'Edited synthetic text '+i}))};
 await assert.rejects(admitSandbox(db,p.id,{...input,schemaVersion:999},true),/changed/);
 await assert.rejects(admitSandbox(db,p.id,{...input,reports:input.reports.map((r,i)=>i===0?{...r,id:reports[0].id}:r)},true),/Only this contest/);
 const admitted=await Promise.all(Array.from({length:10},()=>admitSandbox(db,p.id,input,true)));
 assert.equal(admitted.filter(r=>!r.reused).length,1);const job=admitted[0].job;
 await assert.rejects(admitSandbox(db,p.id,{...input,idempotencyKey:'parallel-run'},true),/already in progress/);
 await assert.rejects(admitSandbox(db,p.id,{...input,prompt:'Changed body'},true),/different input/);
 const other=await sandboxStatus(db,p2.id,contestId);assert.equal(other.job,null);assert.equal(other.inFlight,false);assert.equal(other.reports.length,3);
 const simultaneous=await admitSandbox(db,p2.id,{...input,idempotencyKey:'other-participant'},true);await finishSandbox(db,simultaneous.job.id,'completed');
 await assert.rejects(mutateContestLibrary(db,{action:'activate',contestId,expectedVersion:1}),/in-flight/);
 await assert.rejects(mutateContestLibrary(db,{action:'settings',contestId,expectedVersion:1,evaluationModel:'qwen/qwen3.5-9b',practiceBudget:5}),/in-flight/);
 await assert.rejects(saveContestSchema(db,{action:'schema',contestId,expectedVersion:1,schema}),/in-flight/);
 await appendSandboxResult(db,job.id,{reportId:selected[0],status:'completed',decisions:{}});
 await finishSandbox(db,job.id,'completed');
 const state=await sandboxStatus(db,p.id,contestId);assert.equal(state.job?.status,'completed');assert.equal(state.job?.results.length,1);assert.equal(state.inFlight,false);
 await assert.rejects(admitSandbox(db,p.id,{...input,idempotencyKey:'cooldown-run'},true),/60 seconds/);
 assert.equal((await admitSandbox(db,p.id,input,true)).reused,true);
 // Reopen a DB connection to prove rate control isn't an in-memory clock.
 const fresh=createDatabase();await assert.rejects(admitSandbox(fresh,p.id,{...input,idempotencyKey:'new-tab'},true),/60 seconds/);
 await db.sql("UPDATE sandbox_jobs SET completed_at=now()-interval '61 seconds' WHERE id=$1",[job.id]);
 const next=await admitSandbox(fresh,p.id,{...input,idempotencyKey:'next-run'},true);
 await db.sql("UPDATE sandbox_jobs SET expires_at=now()-interval '1 second' WHERE id=$1",[next.job.id]);
 const recovered=await sandboxStatus(fresh,p.id,contestId);assert.equal(recovered.job?.status,'failed');
 await appendSandboxResult(db,next.job.id,{late:true});assert.deepEqual((await sandboxStatus(db,p.id,contestId)).job?.results,[]);
 await assert.rejects(admitSandbox(db,p.id,{...input,idempotencyKey:'after-crash'},true),/60 seconds/);
 assert.deepEqual(await db.sql('SELECT * FROM reports ORDER BY id'),before);
 assert.deepEqual(await Promise.all(scoredTables.map(t=>db.sql(`SELECT * FROM ${t} ORDER BY 1`))),scoredBefore);
 assert.equal((await db.sql<{n:number}>('SELECT public_submission_limit n FROM challenges WHERE id=$1',[contestId]))[0].n,5);
 console.log('PASS 3/20/77, sample-only read/edit isolation, idempotency race, one in-flight/participant, cooldown persistence, expiry/late-write fence, unrelated participant access, contest-switch fence and unchanged scored tables.');
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>getPool().end());
