import assert from 'node:assert/strict';
import {createDatabase} from '../app/lib/db/database';
import {getPool} from '../app/lib/db/pool';
import {mutateContestLibrary} from '../app/lib/db/contest-library';
import {contestSchemaState,saveContestSchema} from '../app/lib/db/contest-schema';
import {twelveBinaryTemplate} from '../app/lib/contest-schema-fixtures';
async function main(){
 if(process.env.PGDATABASE!=='gpo_freeze_test'||process.env.USE_REAL_LLM==='true')throw new Error('Dedicated disposable DB only');
 const db=createDatabase();
 const schema={...twelveBinaryTemplate,education:{version:1,pipeline:'structured-v1',baselineInstructions:'Synthetic baseline.'}};
 const create=()=>mutateContestLibrary(db,{action:'create',title:'Synthetic freeze fixture',schema,evaluationModel:'qwen/qwen3.5-9b',practiceBudget:5});
 const {contestId:id}=await create();
 const state=()=>contestSchemaState(db,id);
 let s=await state();
 const save=async(action:string,extra:object={})=>{s=await state();return saveContestSchema(db,{action,contestId:id,expectedVersion:s.schema.version,expectedRevision:s.revision,...extra});};
 await save('reports',{reports:Array.from({length:5},(_,i)=>({external_id:`X${i}`,filename:`x${i}.txt`,split:i===0?'public':'private',report_text:'Synthetic knee report.'}))});
 s=await state();
 const detail=await contestSchemaState(db,id,true);
 const editable=detail.reportDetails![0];
 await save('report',{report:{...editable,report_text:'Revised synthetic report.'}});
 assert.equal((await state()).ready,false);
 assert.equal((await contestSchemaState(db,id,true)).reportDetails![0].report_text,'Revised synthetic report.');
 await assert.rejects(save('report',{report:{...editable,id:crypto.randomUUID()}}),/belong/);
 s=await state();
 await save('answers',{answers:s.reports.map(r=>({report_id_or_filename:r.id,answer_values:Object.fromEntries(s.schema.fields.map(f=>[f.key,f.allowedValues![0]]))}))});
 s=await state();
 await mutateContestLibrary(db,{action:'sandbox',contestId:id,expectedVersion:s.schema.version,sandboxEnabled:true,sampleIds:s.reports.filter(r=>r.split==='private').slice(0,3).map(r=>r.id)});
 await db.sql("UPDATE answer_keys SET provenance='clinician_adjudicated',adjudicated_by='Synthetic reviewer',adjudicated_at=now(),import_batch_id='synthetic-batch',notes='Synthetic provenance' WHERE report_id IN (SELECT id FROM reports WHERE challenge_id=$1)",[id]);
 await db.sql('UPDATE challenges SET schema_ready=true WHERE id=$1',[id]);
 await mutateContestLibrary(db,{action:'activate',contestId:id,expectedVersion:1});
 s=await state(); assert.equal(s.frozen,true);assert.equal(s.locked,true);assert.ok(s.configurationFrozenAt);
 assert.equal((await db.sql('SELECT * FROM attempt_reservations WHERE challenge_id=$1',[id])).length,0);
 await assert.rejects(save('schema',{schema}),/locked/);
 await assert.rejects(save('report',{report:{...editable,report_text:'Must not change'}}),/locked/);
 await assert.rejects(mutateContestLibrary(db,{action:'settings',contestId:id,expectedVersion:1,evaluationModel:'qwen/qwen3.5-9b',practiceBudget:9}),/Locked/);
 const blocked=["UPDATE challenges SET public_submission_limit=9 WHERE id=$1","UPDATE challenges SET configuration_frozen_at=NULL,schema_locked=false WHERE id=$1","UPDATE challenges SET instructions='changed' WHERE id=$1","UPDATE challenges SET contest_schema=contest_schema || '{\"title\":\"changed\"}' WHERE id=$1","UPDATE reports SET report_text='changed' WHERE challenge_id=$1","DELETE FROM answer_keys WHERE report_id IN (SELECT id FROM reports WHERE challenge_id=$1)","DELETE FROM challenges WHERE id=$1"];
 for(const q of blocked)await assert.rejects(db.sql(q,[id]),/locked|frozen/i);
 await db.sql("UPDATE challenges SET event_phase='practice_open',event_announcement='hello',event_timer_label='timer',sandbox_enabled=false WHERE id=$1",[id]);
 await mutateContestLibrary(db,{action:'activate',contestId:id,expectedVersion:1});
 assert.equal((await state()).eventPhase,'practice_open','Repeated activation must not pause');
 const before=await db.sql('SELECT * FROM challenges WHERE id=$1',[id]);
 const draft=await save('fork');assert.ok(draft.contestId);
 const d=await contestSchemaState(db,draft.contestId);assert.equal(d.frozen,false);assert.equal(d.locked,false);assert.equal(d.ready,true);assert.equal(d.isActive,false);assert.equal(d.eventPhase,'not_started');assert.equal(d.sandboxSamples.length,3);assert.equal(d.practiceBudget,5);
 assert.deepEqual(await db.sql('SELECT * FROM challenges WHERE id=$1',[id]),before);
 const keys=(cid:string)=>db.sql('SELECT r.external_id,k.answer_values,k.provenance,k.import_batch_id,k.adjudicated_by,k.adjudicated_at,k.notes FROM answer_keys k JOIN reports r ON r.id=k.report_id WHERE r.challenge_id=$1 ORDER BY r.external_id',[cid]);
 assert.deepEqual(await keys(id),await keys(draft.contestId));
 for(const table of ['submissions','prompt_runs','attempt_reservations','sandbox_jobs','participant_attempt_overrides'])assert.equal((await db.sql(`SELECT * FROM ${table} WHERE challenge_id=$1`,[draft.contestId])).length,0);
 const [oldReport]=await db.sql<{id:string}>('SELECT id FROM reports WHERE challenge_id=$1 LIMIT 1',[id]);
 await assert.rejects(db.sql('UPDATE reports SET challenge_id=$2 WHERE id=$1',[oldReport.id,draft.contestId]),/locked/);
 const [oldKey]=await db.sql<{id:string}>('SELECT k.id FROM answer_keys k JOIN reports r ON r.id=k.report_id WHERE r.challenge_id=$1 LIMIT 1',[id]);
 const [draftReport]=await db.sql<{id:string}>('SELECT id FROM reports WHERE challenge_id=$1 LIMIT 1',[draft.contestId]);
 await assert.rejects(db.sql('UPDATE answer_keys SET report_id=$2 WHERE id=$1',[oldKey.id,draftReport.id]),/locked/);
 await mutateContestLibrary(db,{action:'activate',contestId:draft.contestId,expectedVersion:1});
 assert.equal((await state()).frozen,true);assert.equal((await state()).isActive,false);
 await db.sql("UPDATE challenges SET event_phase='ended' WHERE id=$1",[id]);
 await assert.rejects(db.sql("UPDATE challenges SET event_phase='not_started' WHERE id=$1",[id]),/revealed/i);
 await mutateContestLibrary(db,{action:'archive',contestId:id,expectedVersion:1});
 assert.equal((await state()).frozen,true);
 console.log('PASS activation freezes before attempts; DB/API guards; idempotent activation; operational controls; duplicate parity/no history; cross-contest move guarded; permanent freeze/reveal after switching/archive.');
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>getPool().end());
