/** Full schema lifecycle regression: prepare inactive drafts, validate, then activate. */
import assert from 'node:assert/strict';
import {createDatabase} from '../app/lib/db/database';
import {getPool} from '../app/lib/db/pool';
import {contestSchemaState,saveContestSchema} from '../app/lib/db/contest-schema';
import {mutateContestLibrary} from '../app/lib/db/contest-library';
import {twelveBinaryTemplate,mixedTemplate} from '../app/lib/contest-schema-fixtures';
import {reserveAttempt,failReservation} from '../app/lib/db/attempts';
import {submitToSupabase} from '../app/lib/supabase/submission-workflow';
import {getAdminDashboardData} from '../app/lib/supabase/admin-dashboard';
import {createAdminCase} from '../app/lib/supabase/admin-cases';
import {defaultChallengeMode} from '../app/lib/challenge-modes';
import {buildOutputSchema,buildScoredValues} from '../app/lib/schema-storage';
import {scoreModelOutput} from '../app/lib/scoring';
async function main(){
 if(process.env.PGDATABASE!=='gpo_schema_test'||process.env.USE_REAL_LLM==='true')throw new Error('Disposable gpo_schema_test with simulated provider only');
 const db=createDatabase();
 const [participant]=await db.sql<{id:string}>("SELECT id FROM participants WHERE participant_code='P001'");
 const original=await contestSchemaState(db);
 assert.equal(original.frozen,true);
 await assert.rejects(saveContestSchema(db,{action:'schema',contestId:original.contestId,expectedVersion:original.schema.version,schema:twelveBinaryTemplate}),/locked/);
 const fork=async(state:typeof original)=>{
  const created=await saveContestSchema(db,{action:'fork',contestId:state.contestId,expectedVersion:state.schema.version,expectedRevision:state.revision});
  const draft=await contestSchemaState(db,created.contestId);assert.equal(draft.isActive,false);assert.equal(draft.locked,false);return draft;
 };
 let state=await fork(original);
 const initialKeys=(await db.sql<{n:number}>('SELECT count(*)::int n FROM answer_keys k JOIN reports r ON r.id=k.report_id WHERE r.challenge_id=$1',[state.contestId]))[0].n;
 await saveContestSchema(db,{action:'schema',contestId:state.contestId,expectedVersion:state.schema.version,schema:twelveBinaryTemplate});
 state=await contestSchemaState(db,state.contestId);
 assert.equal(state.schema.fields.length,12);assert.equal(state.ready,false);
 assert.equal((await contestSchemaState(db)).contestId,original.contestId);
 assert.equal((await db.sql<{n:number}>('SELECT count(*)::int n FROM answer_keys k JOIN reports r ON r.id=k.report_id WHERE r.challenge_id=$1',[state.contestId]))[0].n,initialKeys);
 await assert.rejects(mutateContestLibrary(db,{action:'activate',contestId:state.contestId,expectedVersion:state.schema.version}),/ready/);
 await assert.rejects(db.sql("UPDATE challenges SET event_phase='practice_open' WHERE id=$1",[state.contestId]),/not ready/);
 const answers=state.reports.map(r=>({report_id_or_filename:r.id,answer_values:Object.fromEntries(state.schema.fields.map(f=>[f.key,'0']))}));
 await assert.rejects(saveContestSchema(db,{action:'answers',contestId:state.contestId,expectedVersion:state.schema.version,answers:answers.slice(1)}),/Every/);
 assert.equal((await db.sql<{n:number}>('SELECT count(*)::int n FROM answer_keys WHERE mode_id=$1 AND schema_version=$2',[state.schema.id,state.schema.version]))[0].n,0);
 await saveContestSchema(db,{action:'answers',contestId:state.contestId,expectedVersion:state.schema.version,answers});
 await mutateContestLibrary(db,{action:'activate',contestId:state.contestId,expectedVersion:state.schema.version});
 state=await contestSchemaState(db);
 assert.equal(state.ready,true);assert.equal(state.frozen,true);
 const legacy={target_mode_id:defaultChallengeMode.id,target_schema_version:defaultChallengeMode.version,target_output_schema:buildOutputSchema(defaultChallengeMode)};
 assert.equal((await db.rpc('admin_update_challenge_schema',legacy)).error?.code,'55000');
 assert.deepEqual((await getAdminDashboardData()).overview.challengeSchema.activationOptions,[]);
 await db.sql("UPDATE challenges SET event_phase='practice_open' WHERE id=$1",[state.contestId]);
 const reservation=await reserveAttempt(db,{challengeId:state.contestId,participantId:participant.id,kind:'public',prompt:'Synthetic test',idempotencyKey:'freeze'});
 await assert.rejects(saveContestSchema(db,{action:'schema',contestId:state.contestId,expectedVersion:state.schema.version,schema:mixedTemplate}),/locked/);
 await assert.rejects(db.sql("UPDATE answer_keys SET answer_values='{}'::jsonb WHERE report_id=$1",[state.reports[0].id]),/locked/);
 await assert.rejects(db.sql("UPDATE reports SET report_text='changed' WHERE id=$1",[state.reports[0].id]),/locked/);
 await failReservation(db,reservation.id);
 await submitToSupabase({kind:'public',participantCode:'P001',prompt:state.schema.fields.map(f=>f.label).join(' '),idempotencyKey:'binary-complete'});
 const binaryId=state.contestId;
 state=await fork(await contestSchemaState(db));assert.equal(state.ready,true);
 await saveContestSchema(db,{action:'schema',contestId:state.contestId,expectedVersion:state.schema.version,schema:mixedTemplate});
 state=await contestSchemaState(db,state.contestId);
 const values=Object.fromEntries(state.schema.fields.map(f=>[f.key,f.type==='number'?10:f.allowedValues[0]]));
 const mixedAnswers=state.reports.map(r=>({report_id_or_filename:r.id,answer_values:{...values}}));
 const invalid=structuredClone(mixedAnswers);invalid[0].answer_values.measurement_1='10';
 await assert.rejects(saveContestSchema(db,{action:'answers',contestId:state.contestId,expectedVersion:state.schema.version,answers:invalid}),/invalid/);
 await saveContestSchema(db,{action:'answers',contestId:state.contestId,expectedVersion:state.schema.version,answers:mixedAnswers});
 // Draft report edits invalidate readiness, then explicit complete revalidation restores it.
 await db.sql("UPDATE reports SET report_text='Synthetic changed report' WHERE id=$1",[state.reports[0].id]);
 assert.equal((await contestSchemaState(db,state.contestId)).ready,false);
 await saveContestSchema(db,{action:'answers',contestId:state.contestId,expectedVersion:state.schema.version,answers:mixedAnswers});
 await mutateContestLibrary(db,{action:'activate',contestId:state.contestId,expectedVersion:state.schema.version});
 await db.sql("UPDATE challenges SET event_phase='practice_open' WHERE id=$1",[state.contestId]);
 await assert.rejects(createAdminCase({filename:'forbidden.txt',split:'public',reportText:'Synthetic',answerKey:values}),/Failed to create report|frozen|locked/i);
 const result=await submitToSupabase({kind:'public',participantCode:'P001',prompt:state.schema.fields.map(f=>f.label).join(' '),idempotencyKey:'mixed-complete'});
 assert.equal(result.score,100);
 const [run]=await db.sql<{schema_snapshot:{fields:unknown[]}}>('SELECT schema_snapshot FROM prompt_runs WHERE challenge_id=$1',[state.contestId]);assert.equal(run.schema_snapshot.fields.length,12);
 const nullable={...values,measurement_1:null};const scored=buildScoredValues(scoreModelOutput(nullable,nullable,state.schema).per_field);
 await assert.rejects(db.transaction(async tx=>{const [item]=await tx.sql<{id:string}>('SELECT i.id FROM prompt_run_items i JOIN prompt_runs r ON r.id=i.prompt_run_id WHERE r.challenge_id=$1 LIMIT 1',[state.contestId]);await tx.sql('UPDATE prompt_run_items SET scored_values=$1::jsonb WHERE id=$2',[JSON.stringify(scored),item.id]);const [stored]=await tx.sql<{scored_values:Record<string,unknown>}>('SELECT scored_values FROM prompt_run_items WHERE id=$1',[item.id]);assert.equal(stored.scored_values.measurement_1,null);throw new Error('rollback fixture');}),/rollback fixture/);
 const weighted=await submitToSupabase({kind:'public',participantCode:'P001',prompt:state.schema.fields.slice(0,8).map(f=>f.label).join(' '),idempotencyKey:'mixed-weighted'});assert.ok(Math.abs(weighted.score-100*13/14)<1e-8);
 assert.equal((await getAdminDashboardData()).overview.testSubmissionsCount,2);
 const race=await Promise.allSettled([reserveAttempt(db,{challengeId:state.contestId,participantId:participant.id,kind:'public',prompt:'race',idempotencyKey:'race'}),saveContestSchema(db,{action:'schema',contestId:state.contestId,expectedVersion:state.schema.version,schema:mixedTemplate})]);assert.equal(race.filter(r=>r.status==='fulfilled').length,1);
 assert.equal((await db.rpc('admin_reset_workshop_run_data')).error,null);
 assert.equal((await db.sql<{n:number}>('SELECT count(*)::int n FROM prompt_runs WHERE challenge_id=$1',[binaryId]))[0].n,1);
 assert.equal((await contestSchemaState(db,state.contestId)).frozen,true);
 console.log('PASS inactive schema/import/revalidation; readiness activation gate; permanent freeze; legacy RPC rejection; binary/mixed numeric weighted scoring; null storage; snapshots; scoped history/reset; admission race.');
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>getPool().end());
